# Default config
server:
  port: 1337

logfile: './log/koop.log'

# the local dir for storing tile files  
data_dir: './local/koop/'
  
# for accessing github 
#github_token: 'XXXXXXXXXXXXXXXXXX'

# the connection to your PostGIS enabled database 
db: 
  postgis: 
    conn: "postgres://norman@localhost/koop"

